# This repo_token should be consistent with the one on the coveralls.io,
# thus the coveralls.io could recognize the test result we send to it.
service_name: travis-ci
repo_token: D0yQbcbiCWCUKIpa9GOsbh07gzlsX7jDk
