FORMAT: 1A
HOST: http://se.zhuangty.com/

# CaμsAPI

CaμsAPI is an API to promote utility learning assistant on wechat end.

## Student Register [/students/register]

### A Student Register [POST]

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key",
            "username": "Valid student username(e.g. 2014000000 or abc14)",
            "password": "Right-password-of-this-id"
        }

+ Response 200 (application/json)

        {
            "message": "Success",
            "username": "Request username",
            "existed": "true or false",
            "information": {
                "studentnumber": "Stundent number",
                "department": "Department",
                "position": "Undergrate/master/doctor/teacher",
                "email": "Email",
                "realname": "Real name"
            }
        }

+ Response 401 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }

## Student Cancel [/students/{username}/cancel]

### A Student Cancel His Register [POST]

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }

+ Response 200 (application/json)

        {
            "message": "Success",
            "username": "Request username"
        }

+ Response 412 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }

## Student Courses List [/learnhelper/{username}/{semester}/courses]

### A Student Get His Courses List [POST]

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }

+ Response 200 (application/json)

        {
            "message": "Success",
            "username": "Request username",
            "courses": [
                {
                    "coursename": "Course Name",
                    "courseid": "Course ID",
                    "unreadnotice": "Unread Notice",
                    "newfile": "New File",
                    "unsubmittedoperations": "Unsubmitted Operations"
                }
            ]
        }

+ Response 412 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }

## Student Course Notices List [/learnhelper/{username}/{semester}/courses/{courseid}/notices]

### Get All Notices Of A Course [POST]

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }

+ Response 200 (application/json)

        {
            "notices": [
                {
                    "title": "Title",
                    "publishtime": "Publish Time",
                    "state": "Read status",
                    "content": "Content"
                }
            ]
        }

+ Response 412 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }

## Student Course Documents List [/learnhelper/{username}/{semester}/courses/{courseid}/documents]

### Get All Documents Of A Course [POST]

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }

+ Response 200 (application/json)

        {
            "documents": [
                {
                    "sequencenum": "Sequence Number",
                    "title": "Title",
                    "explanation": "Brief explanation",
                    "updatingtime": "Updating Time",
                    "state": "New file or not",
                    "size": "Size of file",
                    "url": "File url"
                }
            ]
        }

+ Response 412 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }

## Student Course Assignments List [/learnhelper/{username}/{semester}/courses/{courseid}/assignments]

### Get All Assignments Of A Course [POST]

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }

+ Response 200 (application/json)

        {
            "assignments": [
                {
                    "sequencenum": "Sequence Number",
                    "title": "Title",
                    "detail": "Detail of the assignment",
                    "startdate": "Start date",
                    "duedate": "Due Time",
                    "evaluatingteacher": "Evaluating teacher",
                    "evaluatingdate": "Evaluating date",
                    "comment": "Comment of teacher",
                    "grade": "Grade of the homework"
                }
            ]
        }

+ Response 412 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }

## Student Week Curriculum  [/schedule/{username}/{semester}/{week}]

### Get Curriculum Of A Week [POST]

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }

+ Response 200 (application/json)

        {
            "classes": [
                {
                    "coursid": "Course ID",
                    "coursename": "Course name",
                    "day": "From Monday to Sunday",
                    "class": "From 1 to 6",
                    "teacher": "Teacher",
                    "classroom": "Classroom",
                }
            ]
        }

+ Response 412 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }

## Student Semester Curriculum  [/schedule/{username}/{semester}]

### Get Curriculum Of A Semester [POST]

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }

+ Response 200 (application/json)

        {
            "classes": [
                {
                    "coursid": "Course ID",
                    "coursename": "Course name",
                    "day": "From Monday to Sunday",
                    "class": "From 1 to 6",
                    "teacher": "Teacher",
                    "classroom": "Classroom",
                    "weeks": "Description like 'odd weeks', 'even weeks' and so on"
                }
            ]
        }

+ Response 412 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }

## Update Student Course Info [/update/{username}/courses]

### Call the Server to Update Student Courses Info

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }
        
+ Response 200 (application/json)

        {
            "message": "Request received"
        }

+ Response 412 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }

## Update Student Curriculum Info [/update/{username}/curriculum]

### Call the Server to Update Student Curriculum Info

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }
        
+ Response 200 (application/json)

        {
            "message": "Request received"
        }

+ Response 412 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }


## HS Library [/library/studyrooms]

### Get studyrooms of HS Library [POST]

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }

+ Response 200 (application/json)

        {
            "rooms": [
                {
                    "name": "Name of studyroom",
                    "left": "number of left seats",
                    "used": "number of used seats"
                }
            ]
        }