FORMAT: 1A
HOST: http://se.zhuangty.com/

# CaμsAPI

CaμsAPI is an API to promote utility learning assistant on wechat end.

## User Register [/users/register]

### A User Register [POST]

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key",
            "username": "Valid username(e.g. 2014000000 or abc14)",
            "password": "Right-password-of-this-id"
        }

+ Response 200 (application/json)

        {
            "message": "Success",
            "username": "Request username",
            "existed": "true/false",
            "information": {
                "studentnumber": Stundent number,
                "department": "Department",
                "position": "undergrate/master/doctor/teacher",
                "email": "Email",
                "realname": "Real name"
            }
        }

+ Response 401 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }

## User Cancel [/students/{username}/cancel]

### A User Cancel His Register [POST]

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }

+ Response 200 (application/json)

        {
            "message": "Success",
            "username": "Request username"
        }

+ Response 400 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }

## Student Courses List [/learnhelper/{username}/courses]

### A Student Get His Courses List [POST]

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }

+ Response 200 (application/json)

        {
            "message": "Success",
            "username": "Request username",
            "courses": [
                {
                    "coursename": "Course Name",
                    "courseid": "Course ID",
                    "unreadnotice": Unread Notice Number,
                    "newfile": New File Number,
                    "unsubmittedoperations": Unsubmitted Operations Number
                }
            ]
        }

+ Response 400 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }

## Student Course Notices List [/learnhelper/{username}/courses/{courseid}/notices]

### Get All Notices Of A Course [POST]

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }

+ Response 200 (application/json)

        {
            "message": "Success",
            "username": "Request username",
            "notices": [
                {
                    "sequencenum": Sequence Number,
                    "title": "Title",
                    "publishtime": "Publish Time",
                    "state": "read/unread",
                    "content": "Content"
                }
            ]
        }

+ Response 400 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }

## Student Course Documents List [/learnhelper/{username}/courses/{courseid}/documents]

### Get All Documents Of A Course [POST]

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }

+ Response 200 (application/json)

        {
            "message": "Success",
            "username": "Request username",
            "documents": [
                {
                    "sequencenum": Sequence Number,
                    "title": "Title",
                    "explanation": "Brief explanation",
                    "updatingtime": "Updating Time",
                    "state": "old/previous",
                    "size": "Size of file",
                    "url": "File url"
                }
            ]
        }

+ Response 400 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }

## Student Course Assignments List [/learnhelper/{username}/courses/{courseid}/assignments]

### Get All Assignments Of A Course [POST]

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }

+ Response 200 (application/json)

        {
        
            "message": "Success",
            "username": "Request username",
            "assignments": [
                {
                    "sequencenum": Sequence Number,
                    "title": "Title",
                    "detail": "Detail of the assignment",
                    "startdate": "Start date",
                    "duedate": "Due Time",
                    "evaluatingteacher": "Evaluating teacher",
                    "evaluatingdate": "Evaluating date",
                    "comment": "Comment of teacher",
                    "grade": Grade of the homework
                }
            ]
        }

+ Response 400 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }

## Student Week Curriculum  [/schedule/{username}/{week}]

### Get Curriculum Of A Week [POST]

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }

+ Response 200 (application/json)

        {
            "message": "Success",
            "username": "Request username",
            "classes": [
                {
                    "coursid": "Course ID",
                    "coursename": "Course name",
                    "time": "[[1 to 7,1 to 6]]",
                    "teacher": "Teacher",
                    "classroom": "Classroom"
                }
            ]
        }

+ Response 400 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }

## Student Semester Curriculum  [/schedule/{username}]

### Get Curriculum Of A Semester [POST]

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }

+ Response 200 (application/json)

        {
            "message": "Success",
            "username": "Request username",
            "classes": [
                {
                    "coursid": "Course ID",
                    "coursename": "Course name",
                    "time": "[[1 to 7,1 to 6]]",
                    "teacher": "Teacher",
                    "classroom": "Classroom",
                    "weeks": "array of [1,16]"
                }
            ]
        }

+ Response 400 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }

## Update Student Course Info [/update/{username}/courses]

### Call the Server to Update Student Courses Info

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }
        
+ Response 200 (application/json)

        {
            "message": "Success",
            "username": "Request username"
        }

+ Response 400 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }

## Update Student Curriculum Info [/update/{username}/curriculum]

### Call the Server to Update Student Curriculum Info

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }
        
+ Response 200 (application/json)

        {
            "message": "Success",
            "username": "Request username",
        }

+ Response 400 (application/json)

        {
            "message": "Failure",
            "username": "Request username"
        }


## HS Library [/library/hs]

### Get studyrooms of HS Library [POST]

+ Request (application/json)

        {
            "apikey": "API Key",
            "apisecret": "API Secret Key"
        }

+ Response 200 (application/json)

        {
            "message": "Success",
            "username": "Request username",
            "areas": [
                {
                    "name": "Name of study area",
                    "left": number of left seats,
                    "used": number of used seats
                }
            ]
        }